---
- name: Gather facts
  setup:
    gather_timeout: 5

- name: Add primary administration user
  user:
    name: '{{ provision_username }}'
    groups:
      - ssh
      - sudo
    append: yes
    shell: /bin/bash
    state: present

- name: Ensure sudo is installed
  package:
    name: sudo
    state: present

- name: Ensure group sudo can sudo without password
  lineinfile:
    line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
    regexp: '^%sudo ALL='
    path: /etc/sudoers
    state: present
    validate: /usr/sbin/visudo -c -f %s
...
